name: Build EXE

on:
  push:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build .exe
        run: pyinstaller --onefile main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: daphne-helper-exe
          path: dist/main.exe
