name: Build EXE with Nuitka

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Nuitka and dependencies
        run: |
          pip install nuitka

      - name: Compile with Nuitka
        run: |
          python -m nuitka main.py --standalone --onefile --windows-disable-console --output-filename=daphne_helper.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: daphne-helper-exe
          path: daphne_helper.exe
